language: cpp
compiler: gcc

before_script:
    - sudo apt-get -qq update
    - sudo apt-get -qq install libglew-dev
    - sudo apt-get -qq install libsdl2-dev
    - sudo apt-get -qq install libglm-dev

script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j$(($(nproc)+1))

after_success:
    - cd $TRAVIS_BUILD_DIR/build
    - cpack
