language: cpp
compiler: gcc

script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j$(($(nproc)+1))

after_success:
    - cd $TRAVIS_BUILD_DIR/build
    - cpack
