language: cpp
compiler: gcc

install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install libglew-dev
    - sudo apt-get -qq install libglm-dev
    - curl -O http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
    - tar -xzvf SDL2-2.0.3.tar.gz
    - (cd SDL2-2.0.3 && 3/configure && make && sudo make install)

script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j$(($(nproc)+1))

after_success:
    - cd $TRAVIS_BUILD_DIR/build
    - cpack
